//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alergia_Cliente
    {
        public int Producto_Alergia_Id { get; set; }
        public string Cliente_Username { get; set; }
        public string Nombre { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Producto_Alergia Producto_Alergia { get; set; }
    }
}
