//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descripcion_Cita
    {
        public int Cita_Id { get; set; }
        public int Tipo_Servicio_Id { get; set; }
        public string Nombre_Servicio { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
