//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEFEntities : DbContext
    {
        public BDEFEntities()
            : base("name=BDEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alergia_Cliente> Alergia_Cliente { get; set; }
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Descripcion_Cita> Descripcion_Cita { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Pago_Tarjeta> Pago_Tarjeta { get; set; }
        public virtual DbSet<Producto_Alergia> Producto_Alergia { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
    }
}
