//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago()
        {
            this.Pago_Tarjeta = new HashSet<Pago_Tarjeta>();
        }
    
        public int Id { get; set; }
        public string Tipo_Pago { get; set; }
        public decimal Monto_Total { get; set; }
        public string Numero_Telefono { get; set; }
        public string Clave_Confirmacion { get; set; }
        public int Cita_Id { get; set; }
    
        public virtual Cita Cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago_Tarjeta> Pago_Tarjeta { get; set; }
    }
}
