//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago_Tarjeta
    {
        public int Id { get; set; }
        public string Tipo_Tarjeta { get; set; }
        public string Numero_Tarjeta { get; set; }
        public string Codigo_Autorizacion { get; set; }
        public string Nombre_Cliente { get; set; }
        public int Pago_id { get; set; }
    
        public virtual Pago Pago { get; set; }
    }
}
